### ISSUE TITLE
can't create library for machinekit

### ISSUE THREAD

**Issue by jyapujuju** [kinsamanka/PICnc-V2#1]
sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-key 4955043
gpg: kerserver timed out
gpg: kerserver receive failed: keyserver error
or 
gpgkeys:http fetch error 7:couldn't connect:suceess

while i jump to next line
sudo sh -c 'echo "deb http://0ptr.link/raspbian wheezy main' > \/etc/apt/sources.list.d/rpi-machinekit.list"
\'dquote>

i'm using bananian ... banana pi

**Comment by kinsamanka** [comment]
On Fri, Mar 20, 2015 at 12:33 AM, jyapujuju notifications@github.com
wrote:

> banana pi

You don't need the RPi debs for this board. You can follow the standard
armhf instructions for BBB, this is assuming you have a xenomai kernel for
this board.

## 

GP Orcullo

**Comment by jyapujuju** [comment]
xenomai support for Allwinner A20 sun7i Banana pi board is unknown
https://xenomai.org/pipermail/xenomai/2015-January/033062.html
:(
how can i proceed now??

**Comment by kinsamanka** [comment]
Closing this issue as this is not a PICnc-V2 problem.
