### ISSUE TITLE
Odroid compile vor image

### ISSUE THREAD

**Issue by magnifikus** [kinsamanka/PICnc-V2#2]
Im missing instructions to geht it working in the odroid, i the machinekit image You posted in odroid Forums (from march) but it seems to miss the drivers. Anyone bot an working image or do i have to Compiler linuxcnc myself?

Thanks in advance :)

**Comment by adbensi** [comment]
Hello,
If You have Debian, You not need to build it, You can use debian package or
pre-build image iso. You can build too, but I can make it on Ubuntu with
old machinekit source.

But if You can open machinekit, then You need the picnc SPI source and HAL
files. You find it on the repository. What is Your version of the board?
Em 28/08/2015 15:25, "magnifikus" notifications@github.com escreveu:

**Comment by magnifikus** [comment]
Using debian 7.8 with Linux machinekit 3.10.70-rt71 #1 SMP PREEMPT RT Fri Mar 13 06:54:06 UTC 2015 armv7l GNU/Linux

linuxcnc is sadly reporting as machinekit 0.1 

if i run the test from the wiki its telling me the picnc module is missing, but i have no clue how to compile it and found nothing on the web.

if you have a tip, howto compile it would be nice 

best regards

Moritz Kunze

p.s. tried updating with upgrade, its upgrading the kernel and stops booting as it looks likes, will investigate.

maybe its more resonable to start from vanilla wheezy, apply rt kernel and compile machinekit by hand

**Comment by kinsamanka** [comment]
If you have preempt_rt kernel running on Odriod, you can just follow the
instructions on the machinekit website on using the debian packages.

The 0.1 version is fixed, the actual version can be found on the log file.

Have you built the picnc board?

**Comment by magnifikus** [comment]
yeah i created a prototype, the status is blinking, will experiment abit.

And sorry for spamming issues here

so i found that updating the kernel of the odroid rt-empt image to linux-image-3.10.70-rt71 is causing it to not boot, so i blacklisted that and upgraded the rest.

so my problem is now, machinekit git also has only the hal_spi driver for the raspberry, how do i get the drivers from this repo compiled/integrated, (i have to admit i have not yet a clue about linuxcnc)

something like gcc picnc.c -Llibhal -o picnc.so and copy that to xy would help :)

**Comment by magnifikus** [comment]
seems like its a bummer, kernel upgrade not working and the default kernel is crashing randomly (some kernel panic, could not write down :() 

will try raspberry2, odroid seems to be engineered bad anyway.... guess you can close this :)

**Comment by magnifikus** [comment]
sudo comp --install picnc.c  is btw the command i was looking for ;)
