### ISSUE TITLE
Weired Missplacing

### ISSUE THREAD

**Issue by magnifikus** [kinsamanka/PICnc-V2#3]
Asking if someone uses picncv2 successfull and noticed random displacement of axis during programms.

Config is:
MAX_VELOCITY = 30
MAX_ACCELERATION = 40
STEPGEN_MAXACCEL = 45
SCALE = 640.0

running with G64 P0.05

wired happens sometime during programms, suddenly the X-Axis is ~20mm out of place, maybe someone had this issue also :)

running machinekit on odroid c1 with preempt

best regards

**Comment by adbensi** [comment]
I use, I will simulate this... best regards
Em 09/09/2015 13:24, "magnifikus" notifications@github.com escreveu:

**Comment by kinsamanka** [comment]
Do you observe this problem when using the sim configuration?

Please check the status of the picnc.spi_fault signal.

Asking if someone uses picncv2 successfull and noticed random displacement
of axis during programms.

Config is:
MAX_VELOCITY = 30
MAX_ACCELERATION = 40
STEPGEN_MAXACCEL = 45
SCALE = 640.0

running with G64 P0.05

wired happens sometime during programms, suddenly the X-Axis is ~20mm out
of place, maybe someone had this issue also :)

running machinekit on odroid c1 with preempt

best regards

—
Reply to this email directly or view it on GitHub
https://github.com/kinsamanka/PICnc-V2/issues/3.
