### ISSUE TITLE
Need driver enable control

### ISSUE THREAD

**Issue by n9wxu** [kinsamanka/PICnc-V2#5]
Is the driver enable to be controlled by the PICnc automatically (ie. no steps in a while.. disable the driver) or should the enable outputs be controlled by machinekit?

**Comment by kinsamanka** [comment]
The drive enabled pin is controlled by machinekit. But all the digital outputs are interlocked with the SPI communication, if there's activity on the SPI all the output pins will be cleared.

**Comment by n9wxu** [comment]
So I simply need to map the enables to something in machine kit and the SPI update will drive the enables suitably?

I should probably de-assert the enables should the SPI timeout as well.

**Comment by n9wxu** [comment]
Enable works...
Enable deasserts when the SPI timeouts.
